import { useState, useMemo } from 'react'
import { useTranslation } from 'react-i18next'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { 
  TrendingUp, Sprout, Milk, Landmark, Briefcase, 
  Calendar, Clock, CheckCircle2, AlertCircle, Plus, 
  Search, Filter, Paperclip, Wallet, ChevronDown, ChevronUp, X, Check
} from 'lucide-react'
import type { Transaction, PaymentMode } from '@/shared/types/ledger'
import { useAuthStore } from '@/shared/hooks/useAuthStore'
import { useLedgerStore } from '@/shared/hooks/useLedgerStore'

interface IncomeRegisterViewProps {
  transactions: Transaction[]
  onOpenMoneyInModal: () => void
  onPreviewAttachment: (attachment: any) => void
}

export function IncomeRegisterView({ 
  transactions, 
  onOpenMoneyInModal,
  onPreviewAttachment 
}: IncomeRegisterViewProps) {
  const { i18n } = useTranslation()
  const isMr = i18n.language === 'mr'
  const { user } = useAuthStore()
  const { recordLoanEmiPayment, deleteTransaction } = useLedgerStore()

  const [searchQuery, setSearchQuery] = useState('')
  const [filterCategory, setFilterCategory] = useState<string>('all')

  // EMI Payment Modal State
  const [selectedLoanTx, setSelectedLoanTx] = useState<Transaction | null>(null)
  const [emiAmount, setEmiAmount] = useState('')
  const [emiDate, setEmiDate] = useState(new Date().toISOString().split('T')[0])
  const [emiMode, setEmiMode] = useState<PaymentMode>('bank')
  const [emiNotes, setEmiNotes] = useState('')

  // Filter Income transactions (including parent income and excluding raw auto-generated expense splits for the primary register, but showing deductions clearly)
  const incomeTransactions = useMemo(() => {
    return transactions.filter(tx => 
      tx.type === 'income' && !tx.isAutoGenerated
    )
  }, [transactions])

  const todayStr = new Date().toISOString().split('T')[0]
  const currentMonthKey = todayStr.substring(0, 7) // YYYY-MM
  const currentYearKey = todayStr.substring(0, 4) // YYYY

  // High level KPIs
  const todayIncome = incomeTransactions
    .filter(tx => tx.date === todayStr)
    .reduce((sum, tx) => sum + tx.amount, 0)

  const monthIncome = incomeTransactions
    .filter(tx => tx.date.startsWith(currentMonthKey))
    .reduce((sum, tx) => sum + tx.amount, 0)

  const yearIncome = incomeTransactions
    .filter(tx => tx.date.startsWith(currentYearKey))
    .reduce((sum, tx) => sum + tx.amount, 0)

  const totalNetIncome = incomeTransactions.reduce((sum, tx) => sum + tx.amount, 0)
  const totalGrossIncome = incomeTransactions.reduce((sum, tx) => sum + (tx.grossAmount || tx.amount), 0)
  const totalDeductions = incomeTransactions.reduce((sum, tx) => sum + (tx.totalDeductions || 0), 0)

  const totalFarmExpenses = transactions.filter(tx => tx.type === 'expense').reduce((sum, tx) => sum + tx.amount, 0)
  const netFarmProfit = totalGrossIncome - totalFarmExpenses

  // Category breakdown metrics
  const cropSales = incomeTransactions.filter(tx => tx.incomeCategory === 'crop_sale' || tx.category === 'crop_sale')
  const dairyIncomes = incomeTransactions.filter(tx => tx.incomeCategory === 'dairy' || tx.category.includes('दूध') || tx.category.includes('Dairy'))
  const loanIncomes = incomeTransactions.filter(tx => tx.incomeCategory === 'loan' || tx.category.includes('कर्ज') || tx.category.includes('Loan'))
  const otherIncomes = incomeTransactions.filter(tx => tx.incomeCategory === 'other' || (!tx.incomeCategory && tx.category !== 'crop_sale'))

  const totalCropSaleGross = cropSales.reduce((sum, tx) => sum + (tx.grossAmount || tx.amount), 0)
  const totalCropSaleNet = cropSales.reduce((sum, tx) => sum + tx.amount, 0)
  const totalDairyIncome = dairyIncomes.reduce((sum, tx) => sum + tx.amount, 0)
  const totalLoanReceived = loanIncomes.reduce((sum, tx) => sum + tx.amount, 0)
  const totalOtherIncome = otherIncomes.reduce((sum, tx) => sum + tx.amount, 0)

  // Active Loans & Liabilities Tracker
  const activeLoans = useMemo(() => {
    // Find all loan liability records
    return transactions.filter(tx => 
      tx.autoEntryType === 'loan_outstanding' || 
      (tx.loanDetails && tx.type === 'income')
    )
  }, [transactions])

  // Filtered register transactions
  const filteredRegister = incomeTransactions.filter((tx) => {
    const matchesCat = 
      filterCategory === 'all' || 
      tx.incomeCategory === filterCategory ||
      (filterCategory === 'crop_sale' && tx.category === 'crop_sale')

    const searchLower = searchQuery.toLowerCase()
    const matchesSearch = !searchQuery ||
      (tx.category || '').toLowerCase().includes(searchLower) ||
      (tx.cropName || '').toLowerCase().includes(searchLower) ||
      (tx.partyName || '').toLowerCase().includes(searchLower) ||
      (tx.notes || '').toLowerCase().includes(searchLower) ||
      (tx.billNumber || '').toLowerCase().includes(searchLower)

    return matchesCat && matchesSearch
  })

  // Handle EMI Payment Submit
  const handleEmiSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!user || !selectedLoanTx || !emiAmount || Number(emiAmount) <= 0) return

    await recordLoanEmiPayment(user.mobileNumber, selectedLoanTx.id, {
      amount: Number(emiAmount),
      date: emiDate,
      paymentMode: emiMode,
      notes: emiNotes || `${selectedLoanTx.partyName || 'बँक'} कर्ज हप्ता भरणा`
    })

    setSelectedLoanTx(null)
    setEmiAmount('')
    setEmiNotes('')
  }

  return (
    <div className="flex flex-col gap-5 select-none">
      {/* Header & Quick Action */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
        <div>
          <h2 className="text-lg font-bold text-foreground flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-emerald-600" />
            <span>{isMr ? 'उत्पन्न नोंदवही (Income Register & Money In)' : 'Income Register & Money In'}</span>
          </h2>
          <p className="text-xs text-muted-foreground">
            {isMr 
              ? 'शेतीमाल, दूध, बँक कर्ज व इतर उत्पन्नाचा तपशील आणि नफा-तोटा हिशोब.' 
              : 'Consolidated record of crop sales, dairy, loans, and other farm income.'}
          </p>
        </div>

        <Button
          onClick={onOpenMoneyInModal}
          className="h-10 px-4 rounded-xl text-xs font-bold gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white shadow-md shadow-emerald-600/20"
        >
          <Plus className="h-4 w-4" />
          <span>{isMr ? '+ उत्पन्न नोंदवा (Money In)' : '+ Record Income'}</span>
        </Button>
      </div>

      {/* Primary KPI Cards (5 Metrics) */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        <Card className="rounded-2xl border-emerald-500/20 bg-emerald-500/5 p-3.5 flex flex-col justify-between shadow-sm">
          <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider">
            {isMr ? 'आजचे उत्पन्न' : "Today's Income"}
          </span>
          <span className="text-xl font-black text-emerald-700 dark:text-emerald-400 mt-1">
            ₹{todayIncome.toLocaleString()}
          </span>
          <span className="text-[9px] text-muted-foreground">
            {incomeTransactions.filter(t => t.date === todayStr).length} {isMr ? 'व्यवहार' : 'txns'}
          </span>
        </Card>

        <Card className="rounded-2xl border-emerald-500/20 bg-emerald-500/5 p-3.5 flex flex-col justify-between shadow-sm">
          <span className="text-[10px] font-bold text-emerald-600 uppercase tracking-wider">
            {isMr ? 'या महिन्याचे उत्पन्न' : "This Month"}
          </span>
          <span className="text-xl font-black text-emerald-700 dark:text-emerald-400 mt-1">
            ₹{monthIncome.toLocaleString()}
          </span>
          <span className="text-[9px] text-muted-foreground">
            {new Date().toLocaleString(i18n.language, { month: 'short', year: 'numeric' })}
          </span>
        </Card>

        <Card className="rounded-2xl border-primary/20 bg-primary/5 p-3.5 flex flex-col justify-between shadow-sm">
          <span className="text-[10px] font-bold text-primary uppercase tracking-wider">
            {isMr ? 'या वर्षाचे उत्पन्न' : "This Year"}
          </span>
          <span className="text-xl font-black text-primary mt-1">
            ₹{yearIncome.toLocaleString()}
          </span>
          <span className="text-[9px] text-muted-foreground">{currentYearKey}</span>
        </Card>

        <Card className="rounded-2xl border-border/40 bg-card p-3.5 flex flex-col justify-between shadow-sm">
          <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
            {isMr ? 'एकूण जमा (Money In)' : 'Total Money In'}
          </span>
          <span className="text-xl font-black text-foreground mt-1">
            ₹{totalNetIncome.toLocaleString()}
          </span>
          <span className="text-[9px] text-muted-foreground">
            {isMr ? `एकूण ग्रॉस: ₹${totalGrossIncome.toLocaleString()}` : `Gross: ₹${totalGrossIncome.toLocaleString()}`}
          </span>
        </Card>

        <Card className={`rounded-2xl p-3.5 flex flex-col justify-between shadow-sm border ${
          netFarmProfit >= 0 ? 'border-emerald-500/30 bg-emerald-500/10' : 'border-destructive/30 bg-destructive/10'
        }`}>
          <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            {isMr ? 'निव्वळ नफा (Net Profit)' : 'Net Farm Profit'}
          </span>
          <span className={`text-xl font-black mt-1 ${netFarmProfit >= 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-destructive'}`}>
            {netFarmProfit < 0 ? '-' : ''}₹{Math.abs(netFarmProfit).toLocaleString()}
          </span>
          <span className="text-[9px] text-muted-foreground font-semibold">
            {isMr ? 'उत्पन्न वजा सर्व खर्च' : 'Income less expenses'}
          </span>
        </Card>
      </div>

      {/* Category Breakdown 4-Card Overview */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {/* 1. Crop Sale Card */}
        <Card className="rounded-2xl border-border/60 bg-card p-4 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Sprout className="h-4 w-4 text-emerald-600" />
              {isMr ? 'शेतीमाल विक्री' : 'Crop Sales'}
            </span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-600">
              {cropSales.length} {isMr ? 'नोंदी' : 'sales'}
            </span>
          </div>
          <span className="text-lg font-black text-emerald-600">₹{totalCropSaleNet.toLocaleString()}</span>
          <span className="text-[10px] text-muted-foreground">
            {isMr ? `ग्रॉस: ₹${totalCropSaleGross.toLocaleString()}` : `Gross: ₹${totalCropSaleGross.toLocaleString()}`}
          </span>
        </Card>

        {/* 2. Dairy Income Card */}
        <Card className="rounded-2xl border-border/60 bg-card p-4 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Milk className="h-4 w-4 text-indigo-500" />
              {isMr ? 'दूध व्यवसाय' : 'Dairy Income'}
            </span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-indigo-500/15 text-indigo-600">
              {dairyIncomes.length} {isMr ? 'नोंदी' : 'entries'}
            </span>
          </div>
          <span className="text-lg font-black text-indigo-600">₹{totalDairyIncome.toLocaleString()}</span>
          <span className="text-[10px] text-muted-foreground">
            {isMr ? 'दूध, तूप, पनीर, शेणखत' : 'Milk, Ghee, Manure'}
          </span>
        </Card>

        {/* 3. Loan Received Card */}
        <Card className="rounded-2xl border-border/60 bg-card p-4 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Landmark className="h-4 w-4 text-amber-500" />
              {isMr ? 'बँक कर्ज प्राप्त' : 'Loans Received'}
            </span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-500/15 text-amber-600">
              {loanIncomes.length} {isMr ? 'कर्जे' : 'loans'}
            </span>
          </div>
          <span className="text-lg font-black text-amber-600">₹{totalLoanReceived.toLocaleString()}</span>
          <span className="text-[10px] text-muted-foreground">
            {isMr ? 'पीक कर्ज, मुदत कर्ज' : 'Crop & Term Loans'}
          </span>
        </Card>

        {/* 4. Other / Custom Income Card */}
        <Card className="rounded-2xl border-border/60 bg-card p-4 flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-foreground flex items-center gap-1.5">
              <Briefcase className="h-4 w-4 text-primary" />
              {isMr ? 'इतर / सानुकूल' : 'Other Income'}
            </span>
            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-primary/15 text-primary">
              {otherIncomes.length} {isMr ? 'नोंदी' : 'entries'}
            </span>
          </div>
          <span className="text-lg font-black text-primary">₹{totalOtherIncome.toLocaleString()}</span>
          <span className="text-[10px] text-muted-foreground">
            {isMr ? 'अनुदान, ट्रॅक्टर भाडे, इ.' : 'Subsidies, Rentals, etc.'}
          </span>
        </Card>
      </div>

      {/* Loan & EMI Reminders Section */}
      {activeLoans.length > 0 && (
        <Card className="rounded-2xl border-amber-500/25 bg-amber-500/5 p-4 shadow-sm flex flex-col gap-3">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-amber-800 dark:text-amber-200 flex items-center gap-2">
              <Clock className="h-4 w-4 text-amber-600" />
              <span>{isMr ? 'सक्रिय कर्ज आणि हप्ता रिमाइंडर (Loan & EMI Reminders)' : 'Active Loans & EMI Reminders'}</span>
            </span>
            <span className="text-[10px] font-bold text-amber-700 bg-amber-500/20 px-2 py-0.5 rounded-full">
              {activeLoans.length} {isMr ? 'सक्रिय कर्जे' : 'active loans'}
            </span>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
            {activeLoans.map((loan) => {
              const pending = loan.pendingAmount !== undefined ? loan.pendingAmount : loan.amount
              const isOverdue = loan.dueDate && loan.dueDate < todayStr && pending > 0

              return (
                <div 
                  key={loan.id} 
                  className="p-3 rounded-xl border border-amber-500/20 bg-card flex flex-col gap-2"
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <h4 className="text-xs font-bold text-foreground">{loan.partyName || loan.category}</h4>
                      <span className="text-[10px] text-muted-foreground">
                        {loan.loanDetails?.loanType || (isMr ? 'बँक कर्ज' : 'Bank Loan')}
                        {loan.loanDetails?.interestRate ? ` • ${loan.loanDetails.interestRate}% p.a.` : ''}
                      </span>
                    </div>

                    <div className="text-right">
                      <span className="text-[10px] text-muted-foreground font-semibold block">{isMr ? 'शिल्लक कर्ज' : 'Outstanding'}</span>
                      <span className="text-xs font-black text-destructive">₹{pending.toLocaleString()}</span>
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-1 border-t border-border/40 text-[10px]">
                    <div className="flex items-center gap-1.5 text-muted-foreground">
                      <Calendar className="h-3 w-3" />
                      <span>{isMr ? 'पुढील हप्ता / मुदत:' : 'Due Date:'}</span>
                      <span className={`font-bold ${isOverdue ? 'text-destructive' : 'text-foreground'}`}>
                        {loan.dueDate ? new Date(loan.dueDate).toLocaleDateString(i18n.language, { month: 'short', day: 'numeric', year: 'numeric' }) : '-'}
                      </span>
                    </div>

                    <Button
                      size="sm"
                      onClick={() => {
                        setSelectedLoanTx(loan)
                        setEmiAmount('5000')
                      }}
                      className="h-7 px-2.5 rounded-lg text-[10px] font-bold bg-amber-600 hover:bg-amber-700 text-white"
                    >
                      {isMr ? 'हप्ता भरा' : 'Pay EMI'}
                    </Button>
                  </div>
                </div>
              )
            })}
          </div>
        </Card>
      )}

      {/* Income Register Table */}
      <Card className="rounded-2xl border-border/40 bg-card shadow-sm flex flex-col">
        {/* Filters and Search Bar */}
        <div className="p-4 border-b border-border/20 flex flex-col md:flex-row gap-3 items-center justify-between">
          <div className="flex flex-wrap gap-2 items-center w-full md:w-auto">
            <select
              value={filterCategory}
              onChange={(e) => setFilterCategory(e.target.value)}
              className="h-9 px-2.5 rounded-xl border border-border bg-background text-foreground text-xs font-semibold focus:ring-1 focus:ring-primary outline-none"
            >
              <option value="all">{isMr ? 'सर्व उत्पन्न प्रभाग (All Income)' : 'All Income Types'}</option>
              <option value="crop_sale">{isMr ? 'शेतीमाल विक्री (Crop Sale)' : 'Crop Sales'}</option>
              <option value="dairy">{isMr ? 'दूध व्यवसाय (Dairy)' : 'Dairy Income'}</option>
              <option value="loan">{isMr ? 'कर्ज प्राप्त (Loan)' : 'Loan Received'}</option>
              <option value="other">{isMr ? 'इतर उत्पन्न (Other)' : 'Other Income'}</option>
            </select>
          </div>

          <div className="relative w-full md:w-64 shrink-0">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
            <input
              type="text"
              placeholder={isMr ? 'पीक, ग्राहक, पावती शोधा...' : 'Search crop, customer, bill...'}
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full h-9 pl-9 pr-4 rounded-xl border border-border bg-background text-foreground text-xs font-semibold focus:ring-1 focus:ring-primary outline-none"
            />
          </div>
        </div>

        {/* Transactions list */}
        <div className="divide-y divide-border/20 max-h-[500px] overflow-y-auto">
          {filteredRegister.length > 0 ? (
            filteredRegister.map((tx) => {
              const hasDeductions = (tx.totalDeductions || 0) > 0
              const gross = tx.grossAmount || tx.amount

              return (
                <div key={tx.id} className="p-3.5 sm:p-4 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 hover:bg-muted/10 transition-colors">
                  <div className="flex items-start gap-3 min-w-0">
                    <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 text-emerald-600 flex items-center justify-center shrink-0">
                      {tx.incomeCategory === 'dairy' ? (
                        <Milk className="h-5 w-5" />
                      ) : tx.incomeCategory === 'loan' ? (
                        <Landmark className="h-5 w-5" />
                      ) : tx.incomeCategory === 'other' ? (
                        <Briefcase className="h-5 w-5" />
                      ) : (
                        <Sprout className="h-5 w-5" />
                      )}
                    </div>

                    <div className="flex flex-col min-w-0">
                      <div className="flex flex-wrap items-center gap-1.5">
                        <span className="text-xs font-bold text-foreground">
                          {tx.cropName ? `${tx.cropName} विक्री` : tx.category}
                        </span>

                        <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-md uppercase bg-emerald-500/10 text-emerald-600 border border-emerald-500/20">
                          {tx.incomeCategory?.replace('_', ' ') || 'INCOME'}
                        </span>

                        <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-md uppercase bg-muted text-muted-foreground border border-border/40">
                          {tx.paymentMode || 'BANK'}
                        </span>

                        {tx.billNumber && (
                          <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-md bg-muted/60 text-foreground border border-border/40">
                            #{tx.billNumber}
                          </span>
                        )}
                      </div>

                      <div className="text-[10px] text-muted-foreground font-semibold mt-1 flex flex-wrap items-center gap-2">
                        <span className="flex items-center gap-1">
                          <Calendar className="h-3 w-3" />
                          {new Date(tx.date).toLocaleDateString(i18n.language, { month: 'short', day: 'numeric', year: 'numeric' })}
                        </span>

                        {tx.partyName && (
                          <>
                            <span>•</span>
                            <span className="text-foreground font-bold">👤 {tx.partyName}</span>
                          </>
                        )}

                        {tx.plotName && (
                          <>
                            <span>•</span>
                            <span className="text-primary">📍 {tx.plotName}</span>
                          </>
                        )}

                        {tx.notes && (
                          <>
                            <span>•</span>
                            <span className="italic truncate max-w-xs">{tx.notes}</span>
                          </>
                        )}

                        {tx.attachment && (
                          <button
                            type="button"
                            onClick={() => onPreviewAttachment(tx.attachment)}
                            className="text-primary font-bold hover:underline inline-flex items-center gap-0.5 ml-1"
                          >
                            <Paperclip className="h-3 w-3" />
                            <span>{isMr ? 'पावती' : 'Bill'}</span>
                          </button>
                        )}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 w-full sm:w-auto justify-between sm:justify-end border-t sm:border-t-0 pt-2 sm:pt-0 border-border/20">
                    <div className="text-right">
                      <span className="text-sm font-black text-emerald-600 block">
                        +₹{tx.amount.toLocaleString()}
                      </span>
                      {hasDeductions && (
                        <span className="text-[10px] text-muted-foreground">
                          {isMr ? 'ग्रॉस' : 'Gross'}: ₹{gross.toLocaleString()} (-₹{tx.totalDeductions?.toLocaleString()})
                        </span>
                      )}
                    </div>

                    <button
                      onClick={() => {
                        if (confirm(isMr ? 'हा उत्पन्न व्यवहार कायमचा डिलीट करायचा आहे का?' : 'Are you sure you want to delete this income transaction?')) {
                          user && deleteTransaction(user.mobileNumber, tx.id)
                        }
                      }}
                      aria-label={isMr ? 'व्यवहार डिलीट करा' : 'Delete transaction'}
                      className="text-muted-foreground hover:text-destructive h-8 w-8 rounded-lg flex items-center justify-center hover:bg-accent/40 transition-colors shrink-0"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              )
            })
          ) : (
            <div className="h-56 flex flex-col items-center justify-center text-center p-6 gap-2">
              <TrendingUp className="h-8 w-8 text-muted-foreground/45" />
              <p className="text-xs text-muted-foreground font-bold">
                {isMr ? 'कोणतेही उत्पन्न नोंदी आढळल्या नाहीत.' : 'No income transactions found.'}
              </p>
            </div>
          )}
        </div>
      </Card>

      {/* Pay EMI Modal */}
      {selectedLoanTx && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm p-4 select-none animate-in fade-in duration-200">
          <div className="w-full max-w-md bg-card border border-border rounded-3xl p-6 shadow-2xl relative">
            <button
              onClick={() => setSelectedLoanTx(null)}
              className="absolute right-4 top-4 text-muted-foreground hover:text-foreground h-8 w-8 rounded-full flex items-center justify-center hover:bg-accent/40"
            >
              <X className="h-[18px] w-[18px]" />
            </button>

            <h3 className="text-base font-bold text-foreground mb-1">
              {isMr ? 'कर्ज हप्ता (EMI) भरा' : 'Pay Loan Installment (EMI)'}
            </h3>
            <p className="text-xs text-muted-foreground mb-4">
              {selectedLoanTx.partyName || selectedLoanTx.category}
            </p>

            <form onSubmit={handleEmiSubmit} className="flex flex-col gap-3.5">
              <div className="bg-amber-500/10 border border-amber-500/20 p-3 rounded-xl flex justify-between items-center text-xs">
                <span className="font-semibold text-amber-800 dark:text-amber-200">
                  {isMr ? 'शिल्लक कर्ज दायित्व:' : 'Remaining Liability:'}
                </span>
                <span className="font-black text-amber-800 dark:text-amber-200 text-sm">
                  ₹{(selectedLoanTx.pendingAmount !== undefined ? selectedLoanTx.pendingAmount : selectedLoanTx.amount).toLocaleString()}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="flex flex-col gap-1">
                  <label className="text-xs font-semibold text-foreground">
                    {isMr ? 'हप्ता रक्कम (₹)' : 'EMI Amount (₹)'} <span className="text-destructive">*</span>
                  </label>
                  <input
                    type="number"
                    required
                    min="1"
                    placeholder="₹ 5000"
                    value={emiAmount}
                    onChange={(e) => setEmiAmount(e.target.value)}
                    className="w-full h-10 px-3 rounded-xl border border-border bg-background text-foreground text-sm font-bold focus:ring-1 focus:ring-primary outline-none"
                  />
                </div>

                <div className="flex flex-col gap-1">
                  <label className="text-xs font-semibold text-foreground">
                    {isMr ? 'भरणा तारीख' : 'Payment Date'} <span className="text-destructive">*</span>
                  </label>
                  <input
                    type="date"
                    required
                    value={emiDate}
                    onChange={(e) => setEmiDate(e.target.value)}
                    className="w-full h-10 px-3 rounded-xl border border-border bg-background text-foreground text-xs font-medium focus:ring-1 focus:ring-primary outline-none"
                  />
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <label className="text-xs font-semibold text-foreground">
                  {isMr ? 'पेमेंट प्रकार' : 'Payment Mode'}
                </label>
                <div className="grid grid-cols-4 gap-2">
                  {(['bank', 'upi', 'cash', 'cheque'] as PaymentMode[]).map((m) => (
                    <button
                      key={m}
                      type="button"
                      onClick={() => setEmiMode(m)}
                      className={`h-9 rounded-xl border text-xs font-bold transition-all uppercase ${
                        emiMode === m
                          ? 'border-primary bg-primary/10 text-primary ring-1 ring-primary'
                          : 'border-border bg-background text-muted-foreground hover:bg-muted/30'
                      }`}
                    >
                      {m}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex flex-col gap-1">
                <label className="text-xs font-semibold text-foreground">
                  {isMr ? 'तपशील / पावती क्रमांक' : 'Remarks / Receipt #'}
                </label>
                <input
                  type="text"
                  placeholder={isMr ? 'उदा. ५००० रु. बँक ट्रान्सफर द्वारे भरले' : 'e.g. Paid via NEFT'}
                  value={emiNotes}
                  onChange={(e) => setEmiNotes(e.target.value)}
                  className="w-full h-10 px-3.5 rounded-xl border border-border bg-background text-foreground text-xs font-medium focus:ring-1 focus:ring-primary outline-none"
                />
              </div>

              <div className="flex justify-end gap-2 pt-3 border-t border-border/40 mt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setSelectedLoanTx(null)}
                  className="h-10 px-4 rounded-xl text-xs font-semibold"
                >
                  {isMr ? 'रद्द करा' : 'Cancel'}
                </Button>
                <Button
                  type="submit"
                  className="h-10 px-5 rounded-xl text-xs font-semibold bg-primary text-primary-foreground flex items-center gap-1.5"
                >
                  <Check className="h-4 w-4" />
                  <span>{isMr ? 'हप्ता नोंदवा' : 'Record EMI'}</span>
                </Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
